fiscalite_gestion_fiscalite:
    resource: "@FiscaliteGestionFiscaliteBundle/Resources/config/routing.yml"
    prefix:   /

fiscalite:
    pattern: /fiscalite
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:Index:index }
                
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin   
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
login:
  pattern:  /login
  defaults: { _controller: FOSUserBundle:Security:login }

login_check:
  pattern:  /login_check
  defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
  pattern:  /logout
  defaults: { _controller: FOSUserBundle:Security:logout }