security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    role_hierarchy:
        ROLE_UTILISATEUR: ROLE_USER
        ROLE_ADMIN:       ROLE_UTILISATEUR
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: main
            form_login:
              provider:       fos_userbundle
              login_path:     /fiscalite
              always_use_default_target_path: true
              default_target_path: /fiscalite
              failure_path:   /fiscalite
              use_forward:    false
              check_path:     /login_check
              remember_me : true
            logout:       
              path:   /logout
              target: /fiscalite
              invalidate_session: false
            anonymous:    true
            remember_me:
                path: /fiscalite
                lifetime: 5000
                key:        %secret% 
                
    access_control:
        - { path: ^/error403$, roles: [ ROLE_INACTIVE, ROLE_ACTIVE_CC_PROBLEM, ROLE_ACTIVE_NO_ACCESS ] }
        - { path: ^/fiscalite, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_sonata_admin, role: ROLE_ADMIN }
        - { path: ^/simulationTH, role: ROLE_ADMIN }
        - { path: ^/simulationTF, role: ROLE_ADMIN }
        - { path: ^/taxefonciere, role: ROLE_UTILISATEUR }
        - { path: ^/pdf/$, role: ROLE_UTILISATEUR }
        - { path: ^/csv/$, role: ROLE_UTILISATEUR }
        - { path: ^/taxehabitationliste, role: ROLE_UTILISATEUR }
        - { path: ^/articleTH/$, role: ROLE_UTILISATEUR }
        - { path: ^/articleTF/$, role: ROLE_UTILISATEUR }
        - { path: ^/taxefonciereliste, role: ROLE_UTILISATEUR }
        - { path: ^/resultatTH/$, role: ROLE_ADMIN }
        - { path: ^/resultatTF/$, role: ROLE_ADMIN }
        - { path: ^/secteur, role: ROLE_UTILISATEUR }
        - { path: ^/newsecteur, role: ROLE_UTILISATEUR }
        - { path: ^/articlesecteur/$, role: ROLE_UTILISATEUR }
        - { path: ^/csvListeTF, role: ROLE_UTILISATEUR }
        - { path: ^/pdfArticleTF, role: ROLE_UTILISATEUR }
        - { path: ^/csvArticleTF, role: ROLE_UTILISATEUR }
        - { path: ^/simulationarticletfpdf, role: ROLE_ADMIN }
        - { path: ^/simulationarticletfcsv, role: ROLE_ADMIN }
        - { path: ^/rapportfichier, role: ROLE_UTILISATEUR }
        - { path: ^/admin/$, roles: ROLE_ADMIN }
        - { path: ^/admin/dashboard, roles: ROLE_ADMIN }
        - { path: ^/admin/$, roles: ROLE_ADMIN }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: ROLE_UTILISATEUR }
        - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # -> custom access control for the admin area of the URL
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # -> end
        - { path: ^/, role: ROLE_UTILISATEUR }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
