<?php

namespace Fiscalite\GestionFiscaliteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseRepository extends EntityRepository {

    public function listeNumeroimmeubleaft($term) {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c.numeroimmeubleaft')
                ->where('c.numeroimmeubleaft LIKE :term1')
                ->setParameter('term1', '%' . $term . '%')->addGroupBy('c.numeroimmeubleaft')->addOrderBy('c.numeroimmeubleaft','ASC');
        $arrayAss = $qb->getQuery()
                ->getArrayResult();

        // Transformer le tableau associatif en un tableau standard
        $array = array();
        foreach ($arrayAss as $data) {
            $array[] = $data['numeroimmeubleaft'];
        }

        return $array;
    }

    public function listeLibellevoieaft($term) {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c.libellevoieaft')
                ->where('c.libellevoieaft LIKE :term1')
                ->setParameter('term1', '%' . $term . '%')->addGroupBy('c.libellevoieaft')->addOrderBy('c.libellevoieaft','ASC');
        $arrayAss = $qb->getQuery()
                ->getArrayResult();

        // Transformer le tableau associatif en un tableau standard
        $array = array();
        foreach ($arrayAss as $data) {
            $array[] = $data['libellevoieaft'];
        }

        return $array;
    }

}
