<?php

namespace Fiscalite\GestionFiscaliteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleCommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleCommuneRepository extends EntityRepository {

    public function searchbyfichier($fichier) {
        $qb = $this->createQueryBuilder('a');
        $qb->andWhere('a.fichier =:fichier')
                ->setParameter('fichier', $fichier);

        return $qb->getQuery()->getResult();
    }

    public function searchbyfichierAnneePrecedente($fichier) {
        $qb = $this->createQueryBuilder('a');
        $qb->join('a.fichier', 'f')
                ->andWhere('f.anneetaxation =:anneetaxation')
                ->setParameter('anneetaxation', $fichier->getAnneeTaxation() - 1);

        return $qb->getQuery()->getResult();
    }
    
       public function rechercherFichierAvecAnnee($fichier) {
        $qb = $this->createQueryBuilder('a');
        $qb->join('a.fichier', 'f')
                ->andWhere('f.anneetaxation =:anneetaxation')
                ->setParameter('anneetaxation', $fichier->getAnneeTaxation());
        
        return $qb->getQuery()->getResult();
    }

}
