<?php

namespace Fiscalite\GestionFiscaliteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleTHRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleTHRepository extends EntityRepository {

    public function search($datanumerosequentiel, $datanomprenom, $dataadresse, $dataanneetaxation) {
        $qb = $this->createQueryBuilder('a');
        if ($datanumerosequentiel != NULL) {
            $qb->andWhere('a.numerosequentiel =:numerosequentiel')
                    ->setParameter('numerosequentiel', $datanumerosequentiel);
        }
        if ($datanomprenom != NULL) {
            $qb->andWhere('a.nomprenom LIKE :nomprenom OR a.suitenom LIKE :nomprenom')
                    ->setParameter('nomprenom', '%' . $datanomprenom . '%');
        }
        if ($dataadresse != NULL) {
            $qb->andWhere('a.codevoie LIKE :adresse OR a.numeroimmeubleaft LIKE :adresse OR 
                a.indicederepetition LIKE :adresse OR a.libellevoieaft LIKE :adresse')
                    ->setParameter('adresse', '%' . $dataadresse->getLibellevoieaft() . '%');
        }if ($dataanneetaxation != NULL) {
            $qb->join('a.fichier', 'f1');
            $qb->andWhere('f1.anneetaxation =:ann')
                    ->setParameter('ann', $dataanneetaxation->getAnneetaxation());
        }
        $qb->orderBy('a.nomprenom', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function searchListTH($dataNumeroimmeubleaft, $dataLibellevoieaft, $typerues, $dataSecteur, $dataAnneetaxation, $dataNompersonne, $dataNbpersonnesacharge
    , $dataBasenettemin, $dataBasenettemax, $dataAbattementgeneralbasecommunalemin, $dataAbattementgeneralbasecommunalemax, $dataAbattementpersonneschargecommunalmin, $dataAbattementpersonneschargecommunalmax, $dataAbattementspecialbasecommunalmin, $dataAbattementspecialbasecommunalmax, $dataAbattementspecialhandicapecommunalmin, $dataAbattementspecialhandicapecommunalmax, $dataCotisationcommunalemin, $dataCotisationcommunalemax, $dataMontantnetapayermin, $dataMontantnetapayermax) {


        $qb = $this->createQueryBuilder('a');

        if ($dataSecteur != NULL) {
            $qb->innerJoin('a.adresse', 'adr');
            $qb->innerJoin('adr.typerue', 'typer');
            foreach ($typerues as $typerue) {
                $qb->orWhere('typer.id =:id');
                $qb->setParameter('id', $typerue->getId());
            }
        }
        if ($dataAnneetaxation != NULL) {
            $qb->join('a.fichier', 'f');
            $qb->orWhere('f.anneetaxation =:ann')->setParameter('ann', $dataAnneetaxation->getAnneetaxation());
        }
        if ($dataNompersonne != NULL) {
            $qb->andWhere('a.nomprenom LIKE :nom OR a.suitenom LIKE :nom')
                    ->setParameter('nom', '%' . $dataNompersonne . '%');
        }
        if ($dataNumeroimmeubleaft != NULL) {
            $qb->innerJoin('a.adresse', 'adr');
            $qb->andWhere('adr.numeroimmeubleaft LIKE :numeroimmeubleaft')
                    ->setParameter('numeroimmeubleaft', '%' . $dataNumeroimmeubleaft . '%');
        }
        if ($dataLibellevoieaft != NULL) {
            $qb->innerJoin('a.adresse', 'adr');
            $qb->andWhere('adr.libellevoieaft LIKE :libellevoieaft')
                    ->setParameter('libellevoieaft', '%' . $dataLibellevoieaft . '%');
        }
        if ($dataNbpersonnesacharge != NULL) {
            $qb->join('a.cotisation', 'c3');
            $qb->andWhere('c3.nbpersonnesacharge = :nbpersonnesacharge')
                    ->setParameter('nbpersonnesacharge', $dataNbpersonnesacharge);
        }
        if ($dataBasenettemin != NULL) {
            $qb->join('a.base', 'b1');
            $qb->andWhere('b1.basenettecommunale >= :basenette1')
                    ->setParameter('basenette1', $dataBasenettemin);
        }
        if ($dataBasenettemax != NULL) {
            $qb->join('a.base', 'b2');
            $qb->andWhere('b2.basenettecommunale <= :basenette2')
                    ->setParameter('basenette2', $dataBasenettemax);
        }
        if ($dataAbattementgeneralbasecommunalemin != NULL) {
            $qb->join('a.abattement', 'a1');
            $qb->andWhere('a1.abattementgeneralbasecommunale >= :abattementgeneralbasecommunale1')
                    ->setParameter('abattementgeneralbasecommunale1', $dataAbattementgeneralbasecommunalemin);
        }
        if ($dataAbattementgeneralbasecommunalemax != NULL) {
            $qb->join('a.abattement', 'a2');
            $qb->andWhere('a2.abattementgeneralbasecommunale <= :abattementgeneralbasecommunale2')
                    ->setParameter('abattementgeneralbasecommunale2', $dataAbattementgeneralbasecommunalemax);
        }
        if ($dataAbattementpersonneschargecommunalmin != NULL) {
            $qb->join('a.abattement', 'a3');
            $qb->andWhere('a3.abattementpersonneschargecommunnal >= :abattementpersonneschargecommunnal1')
                    ->setParameter('abattementpersonneschargecommunnal1', $dataAbattementpersonneschargecommunalmin);
        }
        if ($dataAbattementpersonneschargecommunalmax != NULL) {
            $qb->join('a.abattement', 'a4');
            $qb->andWhere('a4.abattementpersonneschargecommunnal <= :abattementpersonneschargecommunnal2')
                    ->setParameter('abattementpersonneschargecommunnal2', $dataAbattementpersonneschargecommunalmax);
        }
        if ($dataAbattementspecialbasecommunalmin != NULL) {
            $qb->join('a.abattement', 'a5');
            $qb->andWhere('a5.abattementspecialbasecommunal >= :abattementspecialbasecommunal1')
                    ->setParameter('abattementspecialbasecommunal1', $dataAbattementspecialbasecommunalmin);
        }
        if ($dataAbattementspecialbasecommunalmax != NULL) {
            $qb->join('a.abattement', 'a6');
            $qb->andWhere('a6.abattementspecialbasecommunal <= :abattementspecialbasecommunal2')
                    ->setParameter('abattementspecialbasecommunal2', $dataAbattementspecialbasecommunalmax);
        }
        if ($dataAbattementspecialhandicapecommunalmin != NULL) {
            $qb->join('a.abattement', 'a7');
            $qb->andWhere('a7.abattementspecialhandicapecommunal >= :abattementspecialhandicapecommunal1')
                    ->setParameter('abattementspecialhandicapecommunal1', $dataAbattementspecialhandicapecommunalmin);
        }
        if ($dataAbattementspecialhandicapecommunalmax != NULL) {
            $qb->join('a.abattement', 'a8');
            $qb->andWhere('a8.abattementspecialhandicapecommunal <= :abattementspecialhandicapecommunal2')
                    ->setParameter('abattementspecialhandicapecommunal2', $dataAbattementspecialhandicapecommunalmax);
        }
        if ($dataMontantnetapayermin != NULL) {
            $qb->andWhere('a.montantnetapayer >= :montantnetapayer1')
                    ->setParameter('montantnetapayer1', $dataMontantnetapayermin);
        }
        if ($dataMontantnetapayermax != NULL) {
            $qb->andWhere('a.montantnetapayer <= :montantnetapayer2')
                    ->setParameter('montantnetapayer2', $dataMontantnetapayermax);
        }
        if ($dataCotisationcommunalemin != NULL) {
            $qb->join('a.cotisation', 'c1')
                    ->andWhere('c1.cotisationcommunale >= :cotisationcommunale1')
                    ->setParameter('cotisationcommunale1', $dataCotisationcommunalemin);
        }
        if ($dataCotisationcommunalemax != NULL) {
            $qb->join('a.cotisation', 'c2')
                    ->andWhere('c2.cotisationcommunale <= :cotisationcommunale2')
                    ->setParameter('cotisationcommunale2', $dataCotisationcommunalemax);
        }
        $qb->orderBy('a.nomprenom', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function findAllOrderbynomprenom() {
        $qb = $this->createQueryBuilder('a');
        $qb->orderby('a.nomprenom', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function findAllOrderbynomprenomlimit() {
        $qb = $this->createQueryBuilder('a');
        $qb->orderby('a.nomprenom', 'ASC')->setMaxResults(500);
        return $qb->getQuery()->getResult();
    }

    public function searchAutreArticle($nomprenom, $suitenom, $libelleaft) {
        $qb = $this->createQueryBuilder('a');
        $year = date("Y") - 2;
        $qb->join('a.fichier', 'f')
                ->andWhere('f.anneetaxation =:year ')
                ->setParameter('year', $year);

        if ($nomprenom != NULL) {
            $qb->andWhere('a.nomprenom =:nomprenom')
                    ->setParameter('nomprenom', $nomprenom);
        }
        if ($suitenom != NULL) {
            $qb->andWhere('a.suitenom =:suitenom')
                    ->setParameter('suitenom', $suitenom);
        }
        if ($libelleaft != NULL) {
            $qb->join('a.adresse', 'adr')
                    ->andWhere('adr.libellevoieaft LIKE :adresse')
                    ->setParameter('adresse', '%' . $libelleaft . '%');
        }
        if ($nomprenom == NULL && $suitenom == NULL && $libelleaft == NULL) {
            $qb = null;
            return $qb;
        }

        return $qb->getQuery()->getResult();
    }

    function couperChaine($chaine, $nbrMotMax) {
        $chaineNouvelle = "";
        $t_chaineNouvelle = explode(" ", $chaine);
        foreach ($t_chaineNouvelle as $cle => $mot) {
            if ($cle < $nbrMotMax) {
                $chaineNouvelle .= $mot . " ";
            }
        }
        return $chaineNouvelle;
    }

    public function searchArticleTH($articletaxationbatis, $articleTF) {
        //prend la chaine sans MR OU MME
        $chaineCouper = $this->couperChaine(substr($articleTF->getTitreEtDesignation(), 4), 2);
        $qb = $this->createQueryBuilder('a')
                ->join('a.fichier', 'f')
                ->andWhere('f.anneetaxation =:year ')
                ->setParameter('year', $articleTF->getFichier()->getAnneetaxation())
                ->join('a.adresse', 'adr')
                ->andWhere('adr.codevoie =:codeVoie ')
                ->setParameter('codeVoie', $articletaxationbatis->getCodeVoie())
                ->andWhere('adr.numeroimmeubleaft =:numeroImmeuble ')
                ->setParameter('numeroImmeuble', $articletaxationbatis->getNumeroImmeuble())
                ->andWhere('adr.indicederepetition =:btq ')
                ->setParameter('btq', $articletaxationbatis->getBtq())
                ->andWhere('a.nomprenom LIKE :nom')
                ->setParameter('nom', '%' . $chaineCouper . '%');
        //TABLEAU DANS $articleTH
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function searchListTHSimulation($secteur, $nom, $prenom, $dataAnneetaxation) {
        $qb = $this->createQueryBuilder('a');
        $qb->join('a.fichier', 'f1');
        $qb->andWhere('f1.anneetaxation =:ann')
                ->setParameter('ann', $dataAnneetaxation);
        if ($nom != NULL) {
            $qb->andWhere('a.nomprenom LIKE :nom')
                    ->setParameter('nom', '%' . $nom . '%');
        }
        if ($prenom != NULL) {
            $qb->andWhere('a.nomprenom LIKE :prenom')
                    ->setParameter('prenom', '%' . $prenom . '%');
        }
        if ($secteur != NULL) {
            foreach ($secteur as $s) {
                $typeRues = $s->getTypeRue();
                if ($typeRues != NULL) {
                    foreach ($typeRues as $typeRue) {
                        $adresses = $typeRue->getAdresses();
                        foreach ($adresses as $adresse) {
                            $article[] = $adresse->getArticleTH();
                        }
                    }
                }
                foreach ($article as $entity) {
                    $qb->andWhere('a.nomprenom LIKE :nomprenom')
                            ->setParameter('nomprenom', '%' . $entity->getNomprenom() . '%');
                }
            }
        }
        return $qb->getQuery()->getResult();
    }

    public function listeNompersonne($term) {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c.nomprenom')
                ->where('c.nomprenom LIKE :term1')
                ->setParameter('term1', '%' . $term . '%')->addGroupBy('c.nomprenom')->addOrderBy('c.nomprenom', 'ASC');
        $arrayAss = $qb->getQuery()
                ->getArrayResult();

        // Transformer le tableau associatif en un tableau standard
        $array = array();
        foreach ($arrayAss as $data) {
            $array[] = $data['nomprenom'];
        }

        return $array;
    }

    public function getArticleStop($relatedfichier) {
        $qb = $this->createQueryBuilder('a');
        $qb->join('a.fichier', 'f')
                ->andWhere('f.nom LIKE :nom ')
                ->setParameter('nom', '%' . $relatedfichier . '%')
                ->addOrderBy('a.numerosequentiel', 'DESC')
                ->setMaxResults(1);
        return $qb->getQuery()->getResult();
    }

}
