<?php

namespace Fiscalite\GestionFiscaliteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FichierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichierRepository extends EntityRepository {

    public function rechercherDernierFichierTF() {
        $value = "TF";
        $qb = $this->createQueryBuilder('f')
                        ->andWhere('f.typeimpot = :string')->setParameter('string', $value)->orderby('f.id', 'DESC')->setMaxResults(1);
        return $qb->getQuery()->getResult();
    }

    public function rechercherDernierFichierTH() {
        $value = "TH";
        $qb = $this->createQueryBuilder('f')
                        ->andWhere('f.typeimpot = :string')->setParameter('string', $value)->orderby('f.id', 'DESC')->setMaxResults(1);
        return $qb->getQuery()->getResult();
    }

    public function getLastYear() {
        $value = "TF";
        $qb = $this->createQueryBuilder('f')
                        ->andWhere('f.typeimpot = :string')->setParameter('string', $value)->groupBy('f.anneetaxation')->orderby('f.anneetaxation', 'DESC')->setMaxResults(1);
        return $qb->getQuery()->getResult();
    }

    public function getLastYearTH() {
        $value = "TH";
        $qb = $this->createQueryBuilder('f')
                        ->andWhere('f.typeimpot = :string')->setParameter('string', $value)->groupBy('f.anneetaxation')->orderby('f.anneetaxation', 'DESC')->setMaxResults(1);
        return $qb->getQuery()->getResult();
    }

}
