<?php

namespace Fiscalite\GestionFiscaliteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecteurRepository extends EntityRepository {

    public function findSecteur($nom, $nombreIndividu, $adresses) {
        $qb = $this->createQueryBuilder('a');
        if ($nom != NULL) {
            $qb->andWhere('a.nom LIKE :nom')
                    ->setParameter('nom', '%' . $nom . '%');
        }
        if ($nombreIndividu != NULL) {
            $qb->andWhere('a.nombreIndividu =:nombreIndividu')
                    ->setParameter('nombreIndividu', $nombreIndividu);
        }
        if ($adresses != NULL) {
            foreach ($adresses as $adresse) {
                $qb->join('a.typerue', 'typerue');
                
            }
            $qb->andWhere('a.sommeAPayer >= :sommeAPayer1')
                    ->setParameter('sommeAPayer1', $dataSommeAPayermin);
        }
  
        $qb->orderBy('a.nom', 'ASC');
        return $qb->getQuery()->getResult();
    }

}
