<?php

namespace Fiscalite\GestionFiscaliteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TFArticleCommune-IFPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TFArticleCommuneIFPRepository extends EntityRepository
{
     public function RechercherTFArticleCommuneIFPAnneePrecedente($fichier){
        $qb = $this->createQueryBuilder('a');
        $qb->join('a.fichier', 'f')
         ->andWhere('f.anneetaxation =:anneetaxation')
        ->setParameter('anneetaxation', $fichier->getAnneeTaxation()-1);
        return $qb->getQuery()->getResult();
    }
}
