<?php

namespace Fiscalite\GestionFiscaliteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TFArticleTaxationBatiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TFArticleTaxationBatiRepository extends EntityRepository
{
    public function listeAdresse($term) {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c.libVoie')
                ->where('c.libVoie LIKE :term1')
                ->setParameter('term1', '%' . $term . '%')->addGroupBy('c.libVoie');
        
        $arrayAss = $qb->getQuery()
                ->getArrayResult();

        // Transformer le tableau associatif en un tableau standard
        $array = array();
        foreach ($arrayAss as $data) {
            $array[] = $data['libVoie'];
        }

        return $array;
    }
}
