<?php

namespace Fiscalite\GestionFiscaliteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeRueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRueRepository extends EntityRepository {

    public function listeTypeRue($term) {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c.libelle')
                ->where('c.libelle LIKE :term1')
                ->setParameter('term1', '%' . $term . '%');
        $arrayAss = $qb->getQuery()
                ->getArrayResult();

        // Transformer le tableau associatif en un tableau standard
        $array = array();
        foreach ($arrayAss as $data) {
            $array[] = $data['libelle'];
        }

        return $array;
    }

    public function findAllGroupByOrderBy() {
        $qb = $this->createQueryBuilder('c')->addGroupBy('c.libelle')->addOrderBy('c.libelle');
      

        return $qb->getQuery()->getResult();
    }

}
