fiscalite_new:
    pattern:  /new/{id}
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:Index:new }
    requirements: { _method: get }
taxefonciere:
    pattern:  /taxefonciere
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeFonciere:index }
pdf:
    pattern:  /pdf/{id}
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeHabitation:pdf }
    requirements: { _method: get }
csv:
    pattern:  /csv/{id}
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeHabitation:csv }
    requirements: { _method: get }  
taxehabitationliste:
    pattern:  /taxehabitationliste
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeHabitation:liste }
articleTH:
    pattern:  /articleTH/{id}
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeHabitation:article }
    requirements: { _method: get }    
taxefonciereliste:
    pattern:  /taxefonciereliste
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeFonciere:liste } 
articleTF:    
    pattern:  /articleTF/{id}
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeFonciere:article }
    requirements: { _method: get }
simulationTH:
    pattern:  /simulationTH
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:Simulation:simulationTH }   
    requirements: { _method: GET|POST }
resultatTH:
    pattern:  /resultatTH/{id}
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:Simulation:resultatTH }  
    requirements: { _method: GET|POST }
simulationTF:
    pattern:  /simulationTF
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:Simulation:simulationTF }   
    requirements: { _method: GET|POST }
resultatTF:
    pattern:  /resultatTF/{id}
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:Simulation:resultatTF }  
    requirements: { _method: GET|POST }    
secteur:
    pattern:  /secteur
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:Secteur:liste }  
newsecteur:
    pattern:  /newsecteur
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:Secteur:new }  
    requirements: { _method: GET|POST }
articlesecteur:
    pattern:  /articlesecteur/{id}
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:Secteur:article }  
    requirements: { _method: GET|POST }
    
fiscalite_ajaxNompersonne:
    pattern: /fiscalite_ajaxNompersonne
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeHabitation:getAjaxResultsNompersonne}
    requirements:
        _method: GET  
fiscalite_ajaxNumeroimmeubleaft:
    pattern: /fiscalite_ajaxNumeroimmeubleaft
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeHabitation:getAjaxResultsNumeroimmeubleaft}
    requirements:
        _method: GET  
fiscalite_ajaxLibellevoieaft:
    pattern: /fiscalite_ajaxLibellevoieaft
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeHabitation:getAjaxResultsLibellevoieaft}
    requirements:
        _method: GET          
fiscalite_ajaxTitreEtDesignation:
    pattern: /fiscalite_ajaxTitreEtDesignation
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeFonciere:getAjaxResultsTitreEtDesignation}
    requirements:
        _method: GET  
fiscalite_ajaxAdresse:
    pattern: /fiscalite_ajaxAdresse
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeFonciere:getAjaxResultsAdresse}
    requirements:
        _method: GET   
fiscalite_ajaxTypeRue:
    pattern: /fiscalite_ajaxTypeRue
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:Secteur:getAjaxResultsTypeRue}
    requirements:
        _method: GET  
csvListeTF:
    pattern:  /csvListeTF
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeFonciere:csvListeTF }
    
pdfArticleTF:   
    pattern:  /pdfArticleTF/{id}
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeFonciere:pdfArticleTF }
    requirements: { _method: get }

csvArticleTF:
    pattern:  /csvArticleTF/{id}
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeFonciere:csvArticleTF }
    requirements: { _method: get }

simulationarticletfpdf:   
    pattern:  /simulationarticletfpdf/{id}
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:Simulation:simulationarticletfpdf }
    requirements: { _method: get }

simulationarticletfcsv:
    pattern:  /simulationarticletfcsv/{id}
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:Simulation:simulationarticletfcsv }    
    requirements: { _method: get }

rapportfichier:
    pattern:  /rapportfichier
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:Index:rapportfichier }

supprimer_simulationTF:
    pattern:  /{id}/supprimerTF
    defaults: { _controller: "FiscaliteGestionFiscaliteBundle:Simulation:supprimerTF" }
    
supprimer_simulationTH:
    pattern:  /{id}/supprimerTH
    defaults: { _controller: "FiscaliteGestionFiscaliteBundle:Simulation:supprimerTH" }    
    
csvSecteurArticleTH:
    pattern:  /csvSecteurArticleTH/{id}
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:Secteur:csvSecteurArticleTH }
    requirements: { _method: get }
    
exportrequetetaxehabitationcsv:
    pattern:  /exportrequetetaxehabitationcsv/{id}
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeHabitation:exportrequetetaxehabitationcsv }
    requirements: { _method: get }

exportrequetetaxefoncierecsv:
    pattern:  /exportrequetetaxefoncierecsv/{id}
    defaults: { _controller: FiscaliteGestionFiscaliteBundle:TaxeFonciere:exportrequetetaxefoncierecsv }
    requirements: { _method: get }    
    
FiscaliteGestionFiscaliteBundle_typerue:
        resource: "@FiscaliteGestionFiscaliteBundle/Resources/config/routing/typerue.yml"
        prefix:   /typerue

fiscalite_maj_typerue:
    pattern:  /typerue/majtyperuejson
    defaults: { _controller: "FiscaliteGestionFiscaliteBundle:TypeRue:majtyperuejson" }    
 
fiscalite_getlatlng:
    pattern:  /secteur/getlatlng
    defaults: { _controller: "FiscaliteGestionFiscaliteBundle:Secteur:getlatlng" }        