parameters:
#    fiscalite_gestion_fiscalite.example.class: Fiscalite\GestionFiscaliteBundle\Example


#    fiscalite_gestion_fiscalite.example:
#        class: %fiscalite_gestion_fiscalite.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]